name: "Sync website"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: "Build MkDocs"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: python -m pip install --upgrade poetry
      - run: poetry install
      - run: poetry run mkdocs build

      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: site/

  deploy:
    name: "Publish Docs"
    needs: build
    
    # See the full reference for available parameters https://docs.int.bayer.com/ref/
    uses: bayer-int/actions-workflows/.github/workflows/publish-docs.yml@main
    with:
      artifact: site
      dir:      site
      preview:  ${{ github.ref != 'refs/heads/main' && github.run_id || '' }}

      # namespace:  'example' # add a custom path your documentation will be available on
